### ISSUE TITLE
Use with imac

### ISSUE THREAD

**Issue by fmpmsilva** [fastfend/homebridge-haieracbridge-platform#4]
Hi,

is there a away to use it with a IMac instead a android device?

thanks.

**Comment by fastfend** [comment]
[See this](https://github.com/fastfend/HaierACBridge/wiki/How-to-install-it-without-Android-device%3F)
Sry for now it is only solution. Can't see any option to change it. I propose using [homebridge-haier-ac](https://github.com/bstuff/haier-ac-remote/tree/master/packages/homebridge-haier-ac) if you have no option to emulate Android device
