### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by AmgFrIt** [fastfend/homebridge-haieracbridge-platform#7]
Hey, on new models of Haier I get this error, mine works with Intelligent Air. Any idea ???

Error: connect ECONNREFUSED 192.168.1.20:56800
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)

**Comment by fastfend** [comment]
Sadly HaierACBridge works only with SmartAir2 App
